name: Docker Build, Release, and Upload to Google Drive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Build Docker image
    - name: Build Docker image
      run: docker build -t my-image-name .

    # Step 3: Get release version (or use commit count for dynamic versioning)
    - name: Get release version
      id: version
      run: |
        if git describe --tags --abbrev=0; then
          echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        else
          echo "VERSION=$(git rev-list --count HEAD)" >> $GITHUB_ENV
        fi

    # Step 4: Upload to Google Drive with dynamic version number
    - name: Upload to Google Drive
      uses: adityak74/google-drive-upload-git-action@v0.3
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        filename: "archive.zip"
        folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        name: "backup_v${{ env.VERSION }}.zip"
        overwrite: "true"
