name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub (or other registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: docker build -t facefusion .

    # Step 4: Push the Docker image to the registry
    - name: Push the Docker image
      run: docker push mstamu831/facefusion
